### ISSUE TITLE
Improve wording of failing regression tests metric

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-report#364]
Current text: “2 van de 300 regressietesten van XYZ slagen niet. 2 van de 300 regressietesten zijn overgeslagen.” It's unclear that the two skipped tests are the same as the two that didn't pass. This is better: “2 van de 300 regressietesten slagen niet omdat ze zijn overgeslagen.”

**Comment by Erik-Stel** [comment]
Proposed text: "2 van de 300 regressietesten van XYZ slagen niet en 3 regressietesten worden overgeslagen." or in case of the previous example: "Alle regressietesten van XYZ slagen en 2 regressietesten worden overgeslagen". This way it is simply an addition of two messages. Also the statement "2 van de 300 regressietesten slagen niet omdat ..." seems to imply failure instead of skipping which was the reason people got confused in the first place.
